# Generated by Django 3.1.1 on 2020-10-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cesta',
            name='ce_status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cesta',
            name='ce_total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='compra',
            name='com_total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='compra',
            name='us_rut',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='det_can',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='det_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='det_status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='detcom_can',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='detcom_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='key',
            name='compra_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='key',
            name='key_desc',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transacciones',
            name='comp_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transacciones',
            name='tr_met_pago',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transacciones',
            name='tr_mon',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transacciones',
            name='us_rut',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='us_rut',
            field=models.IntegerField(),
        ),
    ]
