# Generated by Django 3.1.1 on 2020-10-20 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0002_auto_20201017_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='desc_reg',
            field=models.CharField(max_length=40, verbose_name='Nombre de region'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_ciud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='modelo.ciudad', verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='modelo.rol', verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='us_apes',
            field=models.CharField(max_length=40, verbose_name='Capellido'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='us_contr',
            field=models.CharField(max_length=20, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='us_creac',
            field=models.DateField(verbose_name='Creacion de usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='us_dir',
            field=models.CharField(max_length=50, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='us_mail',
            field=models.EmailField(max_length=254, verbose_name='Mail'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='us_nac',
            field=models.DateField(verbose_name='Nacimiento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='us_nom',
            field=models.CharField(max_length=20, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='us_rut',
            field=models.IntegerField(verbose_name='Rut'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='us_sald',
            field=models.IntegerField(verbose_name='Saldo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='us_tel',
            field=models.IntegerField(verbose_name='Telefono'),
        ),
    ]
