# Generated by Django 3.1.2 on 2020-11-05 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modelo', '0003_auto_20201020_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='us_contr',
        ),
        migrations.AddField(
            model_name='usuario',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='det_can',
            field=models.IntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='det_price',
            field=models.IntegerField(verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='det_status',
            field=models.IntegerField(verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='j_desc',
            field=models.CharField(max_length=2000, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='j_fe_sal',
            field=models.DateField(verbose_name='Fecha de salida'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='j_nom',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='j_plt',
            field=models.CharField(max_length=10, verbose_name='Plataforma'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='j_port',
            field=models.CharField(max_length=10, verbose_name='Nombre de portada'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='j_price',
            field=models.IntegerField(verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='j_status',
            field=models.IntegerField(verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='j_stock',
            field=models.IntegerField(verbose_name='Stock'),
        ),
    ]
