# Generated by Django 3.1.2 on 2020-11-04 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0003_auto_20201020_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='det_can',
            field=models.IntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='det_price',
            field=models.IntegerField(verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='det_status',
            field=models.IntegerField(verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='j_desc',
            field=models.CharField(max_length=2000, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='j_fe_sal',
            field=models.DateField(verbose_name='Fecha de salida'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='j_nom',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='j_plt',
            field=models.CharField(max_length=10, verbose_name='Plataforma'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='j_port',
            field=models.CharField(max_length=10, verbose_name='Nombre de portada'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='j_price',
            field=models.IntegerField(verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='j_status',
            field=models.IntegerField(verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='j_stock',
            field=models.IntegerField(verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='us_apes',
            field=models.CharField(max_length=40, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='us_rut',
            field=models.CharField(max_length=9, verbose_name='Rut'),
        ),
    ]
