# Generated by Django 3.1.2 on 2020-11-05 03:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modelo', '0004_auto_20201105_0026'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='perfil',
        ),
    ]
