# Generated by Django 3.1.2 on 2020-11-05 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0005_auto_20201105_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='user',
        ),
        migrations.AddField(
            model_name='perfil',
            name='nom_user',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
