# Generated by Django 3.1.2 on 2020-11-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0007_auto_20201106_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='id_rol',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='us_sald',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='us_apes',
            field=models.CharField(max_length=40, verbose_name='Apellido'),
        ),
    ]
