# Generated by Django 3.1.2 on 2020-11-07 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0008_auto_20201106_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='us_creac',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='us_mail',
        ),
    ]
