# Generated by Django 3.1.2 on 2020-11-08 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0009_auto_20201106_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ciudad',
            old_name='id_ciu',
            new_name='id_ciud',
        ),
    ]
