# Generated by Django 3.1.2 on 2020-11-08 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0010_auto_20201107_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='us_rut',
            field=models.CharField(max_length=9, verbose_name='Rut'),
        ),
    ]
