# Generated by Django 3.1.2 on 2020-11-09 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0011_auto_20201107_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ciudad',
            old_name='id_ciud',
            new_name='id_ciu',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='us_rut',
            field=models.IntegerField(verbose_name='Rut'),
        ),
    ]
