# Generated by Django 3.1.2 on 2020-11-09 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0012_auto_20201108_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='j_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='modelo.juego'),
        ),
        migrations.AddField(
            model_name='compra',
            name='j_port',
            field=models.CharField(max_length=10, null=True, verbose_name='Nombre de portada'),
        ),
        migrations.AddField(
            model_name='compra',
            name='nom_user',
            field=models.CharField(max_length=20, null=True, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='com_id',
            field=models.AutoField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
