# Generated by Django 3.1.2 on 2020-11-09 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0014_auto_20201108_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='fotoPerfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_user', models.CharField(blank=True, max_length=20, null=True, verbose_name='username')),
                ('foto_perfil', models.ImageField(upload_to='uploads')),
                ('foto_banner', models.ImageField(upload_to='uploads')),
            ],
        ),
    ]
