# Generated by Django 3.1.2 on 2020-11-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0015_fotoperfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='com_cod',
        ),
        migrations.AddField(
            model_name='compra',
            name='j_plt',
            field=models.CharField(max_length=10, null=True, verbose_name='Plataforma'),
        ),
    ]
