# Generated by Django 3.1.2 on 2020-11-09 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0016_auto_20201109_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='id_reg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='modelo.region', verbose_name='Región'),
        ),
    ]
