# Generated by Django 3.1.2 on 2020-11-10 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0017_perfil_id_reg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='us_rut',
            field=models.CharField(max_length=9, verbose_name='Rut'),
        ),
    ]
