# Generated by Django 3.1.2 on 2020-11-10 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0018_auto_20201109_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ciudad',
            old_name='id_ciu',
            new_name='id_ciud',
        ),
    ]
