# Generated by Django 3.1.2 on 2020-11-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0021_auto_20201122_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='j_port',
            field=models.ImageField(upload_to='juegos'),
        ),
    ]
