# Generated by Django 3.1.2 on 2020-12-01 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0022_auto_20201122_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='us_nac',
            field=models.DateTimeField(verbose_name='Nacimiento'),
        ),
    ]
