# Generated by Django 3.1.2 on 2020-12-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0023_auto_20201130_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='us_nac',
            field=models.DateField(verbose_name='Nacimiento'),
        ),
    ]
